#!/bin/bash
# SDL2 환경변수 한 방에 설정

export DISPLAY=:0
export SDL_VIDEODRIVER=x11
export SDL_RENDER_DRIVER=software
export LIBGL_ALWAYS_INDIRECT=0
export LIBGL_ALWAYS_SOFTWARE=1

echo "✅ SDL 환경변수 설정 완료"
echo "DISPLAY=$DISPLAY"
echo "SDL_VIDEODRIVER=$SDL_VIDEODRIVER"
echo "SDL_RENDER_DRIVER=$SDL_RENDER_DRIVER"
echo "LIBGL_ALWAYS_INDIRECT=$LIBGL_ALWAYS_INDIRECT"
echo "LIBGL_ALWAYS_SOFTWARE=$LIBGL_ALWAYS_SOFTWARE"

